### ISSUE TITLE
Entries in manifest need commas

### ISSUE THREAD

**Issue by xisx** [Announcement/Readerly#1]
Talking about:
  "web_accessible_resources": [
    "distribution/fonts/*",
    "distribution/images/*",
    "distribution/lib/*",
    "distribution/*"
  ],

**Comment by Announcement** [comment]
The main manifest.json is now found in [distribution](https://github.com/Announcement/Readerly/blob/master/distribution/manifest.json)

Does this meet the requested changes?

**Comment by xisx** [comment]
Yep.
